<?php
require('FPDF/fpdf.php');
include('db.php');
session_start();
// Check if the user is logged in
if (isset($_SESSION['id'])) {
    // You can access session data like this
    $userId = $_SESSION['id'];
    $username = $_SESSION['username'];
    $userType = $_SESSION['usertype'];

    //echo "Welcome, $username!";  // Display username
} else {
    // User is not logged in, redirect to login page
    header('Location: ../user/login.php');
    exit;
}
// Retrieve username from session
$user_name = isset($_SESSION['username']) ? $_SESSION['username'] : 'Guest'; // Default to 'Guest' if not set
class PDF extends FPDF {
    function Header() {
        $this->SetFont('Arial','B',12);
        $this->Cell(0,10,'Exported Table Data',0,1,'C');
    }
    
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,10,'Page '.$this->PageNo(),0,0,'C');
    }
    function BackgroundImage($imagePath) {
        $this->Image($imagePath, 0, 0, 210, 297); // Adjust dimensions to fit A4 size
    }
}

$pdf = new PDF();
$pdf->AddPage();
// Set background image
$pdf->BackgroundImage('../Front/Resource/images/a3logo.png'); // Adjust the path to your image

// Title
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'TI and SWIFT Weekly Report',0,1,'C'); // Title centered

// Date and Username
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,10,'Date Generated: ' . date('Y-m-d'),0,0,'L'); // Date on the left
$pdf->Cell(0,10,'Generated by: ' . $user_name,0,1,'R'); // Username on the right
$pdf->Ln(10); // Add some space after the header



$pdf->SetFont('Arial','',12);

// Retrieve parameters

$type = isset($_GET['type']) ? mysqli_real_escape_string($conn, $_GET['type']) : '';
$area = isset($_GET['area']) ? mysqli_real_escape_string($conn, $_GET['area']) : '';
$subject = isset($_GET['subject']) ? mysqli_real_escape_string($conn, $_GET['subject']) : '';
$detail = isset($_GET['detail']) ? mysqli_real_escape_string($conn, $_GET['detail']) : '';
$date = isset($_GET['date']) ? mysqli_real_escape_string($conn, $_GET['date']) : '';
$uname = isset($_GET['uname']) ? mysqli_real_escape_string($conn, $_GET['uname']) : '';


// Query your database to get data based on the parameters
// Prepare the query
$query = "SELECT *  FROM report WHERE 1=1"; // Start with a basic query
if (!empty($type)) {
    $query .= " AND Reporttype = '$type'";
}
if (!empty($area)) {
    $query .= " AND area = '$area'";
}
if (!empty($subject)) {
    $query .= " AND uname = '$subject'";
}
if (!empty($detail)) {
    $query .= " AND uname = '$detail'";
}
if (!empty($date)) {
    $query .= " AND Creationdate = '$date'";
}
if (!empty($uname)) {
    $query .= " AND uname = '$uname'";
}
// Execute the query
$result = mysqli_query($conn, $query);
// Check for query execution errors
if (!$result) {
    die('Query Failed: ' . mysqli_error($conn));
}
// Example data
$data = [
    ['type' => $type, 'area' => $area,'subject'=>$subject, 'date' => $date, 'uname' => $uname],
    // Fetch actual data from your database
];

// Prepare the PDF table
$pdf->SetFillColor(200, 220, 255);
$pdf->Cell(40,10,'Type',1,0,'C',1);
$pdf->Cell(40,10,'Area',1,0,'C',1);
$pdf->cell(40,10,'Subject',1,0,'C',1);
$pdf->Cell(40,10,'Date',1,0,'C',1);
$pdf->Cell(40,10,'Username',1,1,'C',1);

// Fetch the results and add them to the PDF
while ($row = mysqli_fetch_assoc($result)) {
    $pdf->Cell(40,10,$row['Reporttype'],1);
    $pdf->Cell(40,10,$row['area'],1);
    $pdf->Cell(40,10,$row['Reportsubject'],1);
    $pdf->Cell(40,10,$row['Creationdate'],1);
    $pdf->Cell(40,10,$row['uname'],1);
    $pdf->Ln();
}

$pdf->Output('D', 'table-data.pdf');
?>